### ISSUE TITLE
Time Format Issu

### ISSUE THREAD

**Issue by hphp22f** [Xposed-Modules-Repo/its.madruga.wpp#5]
Using the module time format becomes "24-hour 13:00" hours without AM & PM, please change the time format to "12-hour 1:00PM" hours.

**Comment by Shubhamkr4** [comment]
Yes plz fix this soon

**Comment by ItsMadruga** [comment]
A button was added to choose the format, but it has an error in the translation. To obtain the time in 12 hours, activate the 24-hour button in the customization tab.
