### ISSUE TITLE
Send messages edit not working 

### ISSUE THREAD

**Issue by Mehedi5585** [Xposed-Modules-Repo/its.madruga.wpp#6]
When using this module I use the "Hide Forwarding Tag" feature while the message editing option does not work.

https://github.com/Xposed-Modules-Repo/its.madruga.wpp/assets/117540245/77371365-f3dc-4407-831d-69a04c35ecd2

**Comment by ItsMadruga** [comment]
Download the new update, it has been fixed

**Comment by Mehedi5585** [comment]
> Download the new update, it has been fixed

Thanks,Dear
