### ISSUE TITLE
Feature request: Can't see when some people last seen, 

### ISSUE THREAD

**Issue by Mehedi5585** [Xposed-Modules-Repo/its.madruga.wpp#9]
Can't see when some people last seen, add a feature to see everyone's last seen.
![Screenshot_2024-02-11-14-22-20-406_com whatsapp](https://github.com/Xposed-Modules-Repo/its.madruga.wpp/assets/117540245/99dede42-d25f-4001-8ee4-c3dfe420d0ee)

**Comment by ItsMadruga** [comment]
If you are hiding your status information, you also cannot see other people's status information.
